In [1]:
import numpy as np

In [2]:
"Punto 3: Multiplicacion de matrices"
def Multiplicar_matrices (A,B):
    respuesta= np.zeros((len(A),len(B[0])))
    if len(A[0]) == len(B):
        for i in range(0,len(A)):
            for j in range(0,len(B[0])):
                for k in range(0,len(B)):
                    respuesta[i][j]+=A[i][k]*B[k][j]
    else:
     print("No se puede realizar la multiplicación.")
    return respuesta

In [3]:
A= np.array([[1,0,0],[5,1,0],[-2,3,1]])
B= np.array([[4,-2,1],[0,3,7],[0,0,2]])
print(Multiplicar_matrices(A, B))    

[[ 4. -2.  1.]
 [20. -7. 12.]
 [-8. 13. 21.]]
