In [6]:
import numpy as np

In [8]:
def lu_factorization(A):
    n = A.shape[0]
    L = np.eye(n)
    U = np.copy(A)
    
    for j in range(n):
        for i in range(j+1, n):
            L[i, j] = U[i, j] / U[j, j]
            U[i, j:n] = U[i, j:n] - L[i, j] * U[j, j:n]
    
    return np.matrix(L), np.matrix(U)

A = np.array([[4, -2, 1], [20, -7, 12], [-8, 13, 17]])
L, U = lu_factorization(A)
print("L:", L)
print("U:", U)

L: [[ 1.  0.  0.]
 [ 5.  1.  0.]
 [-2.  3.  1.]]
U: [[ 4 -2  1]
 [ 0  3  7]
 [ 0  0 -2]]
