In [77]:
import numpy as np
import matplotlib.pyplot as plt

In [78]:
def metodo_jacobi(A, iteraciones=1000):
    dimension = A.shape[0]
    Id = np.identity(dimension)
    contador = 0
    
    while contador < iteraciones:
        indice_maximo = (0, 0)
        valor_maximo = 0
        for i in range(dimension):
            for j in range(i+1, dimension):
                valor = np.abs(A[i][j])
                if valor > valor_maximo:
                    valor_maximo = valor
                    indice_maximo = (i,j)
        i = indice_maximo[0]
        j = indice_maximo[1]

        if A[i][i] == A[j][j]:
            theta = np.pi / 4
        else:
            x = (2 * A[i][j]) / (A[j][j] - A[i][i]) 
            if x >= 0:
                theta = 0.5 * np.arctan(x)
            else:
                theta = 0.5 * np.arctan(x) + np.pi
            
        c = np.cos(theta)
        s = np.sin(theta)
        M_rotacion = np.eye(dimension)
        M_rotacion[i][i] = c
        M_rotacion[j][j] = c
        M_rotacion[i][j] = s
        M_rotacion[j][i] = -s


        A = np.dot(M_rotacion.T, np.dot(A, M_rotacion))
        Id = np.dot(Id, M_rotacion)
        contador += 1

    valores_propios = np.diag(A)
    vectores_propios = Id

    return valores_propios, vectores_propios

In [79]:
A = np.array([[4, 1, 1], [1, 3, 2], [1, 2, 5]])

print(metodo_jacobi(A))

(array([3.39729507, 1.70759841, 6.89510652]), array([[-0.88573564,  0.17059871,  0.43170413],
       [ 0.07589338, -0.86427949,  0.49725362],
       [ 0.45794385,  0.47319874,  0.75257583]]))


In [80]:
#Prueba con np.linalg.eig

valores, vectores = np.linalg.eig(A)
print(valores)
print(vectores)

Se presentan algunos errores de signos en el metodo_jacobi

[6.89510652 3.39729507 1.70759841]
[[ 0.43170413  0.88573564  0.17059871]
 [ 0.49725362 -0.07589338 -0.86427949]
 [ 0.75257583 -0.45794385  0.47319874]]
